language: elixir
elixir:
  - 1.3.4
  - 1.4
  - 1.5
otp_release:
  - 18.3
  - 19.3
  - 20.0

matrix:
  allow_failures:
    - elixir: 1.3.4

notifications:
  email:
    - mitch@rokkincat.com
script:
  - mix test
  - mix credo
